version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - /app/node_modules # anonymous volume for node_modules only
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
